# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brewboard < Formula
  desc "Keyboard-first terminal interface for routine Homebrew maintenance"
  homepage "https://github.com/KaanEmec/brew-board"
  version "1.0.0-rc.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/KaanEmec/brew-board/releases/download/v1.0.0-rc.2/brewboard_1.0.0-rc.2_darwin_amd64.tar.gz"
    sha256 "5b85fb036f9a83bed71b09d6e612f24a90a8b0b5a12b6a6ebe07e5e3306f05d8"

    define_method(:install) do
      bin.install "brewboard"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/KaanEmec/brew-board/releases/download/v1.0.0-rc.2/brewboard_1.0.0-rc.2_darwin_arm64.tar.gz"
    sha256 "d5aa31aa4ccceb3488c4f7a30de77723f41876e61754aeed0e7982bde98f243b"

    define_method(:install) do
      bin.install "brewboard"
    end
  end

  test do
    system "#{bin}/brewboard", "--version"
  end
end
